/**
 * Zentrale, frameworkunabhängige Inhalte der Lupercia-Startseite.
 * Unbestätigte oder noch nicht verfügbare Angebote sind explizit modelliert.
 */
export const siteContent = Object.freeze({
  brand: {
    name: 'Lupercia',
    claim: 'Tee. Genuss. Begegnung.',
    location: 'Bonn · Südstadt',
  },
  locale: {
    current: 'de',
    available: ['de'],
    planned: ['en', 'es'],
  },
  navigation: [
    { id: 'salon', label: 'Salon', href: '/salon/', status: 'available' },
    { id: 'tea', label: 'Tee & Genuss', href: '/tee-genuss/', status: 'available' },
    { id: 'events', label: 'Veranstaltungen', href: '/veranstaltungen/', status: 'available' },
    { id: 'maria', label: 'Maria', href: '/maria/', status: 'available' },
    { id: 'gift-box', label: 'Geschenkbox', href: '#geschenkbox', status: 'coming-soon' },
    { id: 'visit', label: 'Besuch', href: '/salon/#besuch', status: 'available' },
  ],
  eventSystem: {
    categories: ['Verkostung', 'Workshop', 'Teerunde', 'Frauenrunde', 'Leserunde', 'Tango', 'Seminar', 'Sonstiges'],
    statuses: ['upcoming', 'sold-out', 'past', 'coming-soon'],
    routeBase: '/veranstaltungen/',
  },
  maria: {
    name: 'Maria Moreno',
    role: 'Tee-Sommelière',
    positioning: 'Lupercia ist Marias persönliche Welt des Tees.',
    roles: ['Tee-Sommelière', 'Gastgeberin', 'Kuratorin', 'Persönliche Ansprechpartnerin'],
    knownStory: {
      grandmotherTeaHours: true,
      nameCarriesFamilyMemory: true,
      argentinianConnection: true,
    },
  },
  salonVisit: {
    roomPhotography: { src: null, alt: null, status: 'awaiting-original' },
    address: { value: 'Argelanderstraße 75, 53115 Bonn', href: 'https://www.google.com/maps/place//data=!4m2!3m1!1s0x47bee1319e495c77:0x1469500b6761ac3c', status: 'available' },
    openingHours: { value: { monday: null, tuesday: '11:00–19:00', wednesday: '11:00–19:00', thursday: '11:00–19:00', friday: '11:00–19:00', saturday: '12:00–17:00', sunday: null }, status: 'available' },
    phone: { label: '01516 7970350', href: 'tel:+4915167970350', status: 'available' },
    email: { label: 'E-Mail', href: null, status: 'not-provided' },
    reservation: { href: null, status: 'coming-soon' },
    accessibility: { value: null, status: 'coming-soon' },
    map: { embed: null, provider: null, consentRequired: true, status: 'not-configured' },
  },
  conversionActions: {
    reservation: { label: 'Tisch reservieren', href: null, status: 'coming-soon' },
    event: { viewLabel: 'Event ansehen', bookingLabel: 'Event anmelden' },
    giftBox: { label: 'Geschenkbox anfragen', href: null, status: 'coming-soon' },
    visit: { label: 'Lupercia besuchen', href: '/salon/#besuch', status: 'available' },
  },
  teaOfTheDay: {
    name: null,
    origin: null,
    flavorProfile: [],
    image: null,
    active: false,
    fallback: 'Die heutige Auswahl erfahren Sie direkt im Salon.',
  },
  teaEnjoyment: {
    positioning: 'Tee steht im Mittelpunkt. Argentinien gibt Lupercia seine persönliche Handschrift.',
    teaFamilies: [
      { name: 'Schwarzer Tee', note: 'Kräftig, malzig oder fein und duftig.' },
      { name: 'Grüner Tee', note: 'Frisch, klar und vielschichtig.' },
      { name: 'Weißer Tee', note: 'Sanft, floral und zurückhaltend.' },
      { name: 'Kräuter & Früchte', note: 'Duftende Mischungen für jede Tageszeit.' },
      { name: 'Weitere Entdeckungen', note: 'Wechselnde Sorten, persönlich ausgewählt.' },
    ],
    tableware: {
      regions: ['England', 'Deutschland', 'weitere europäische Hersteller'],
      status: 'curated-selection',
    },
    delicacies: ['Scones mit Clotted Cream', 'Argentinisches Gebäck', 'Sandwiches', 'Marmelade', 'Hausgemachter Kuchen'],
    teaTime: {
      reservation: null,
      status: 'coming-soon',
    },
  },
  productWorld: [
    {
      id: 'tea',
      eyebrow: '01 — Tee',
      title: 'Tee ist unser Mittelpunkt.',
      text: 'Bio-Tee sowie ausgewählte Schwarz-, Grün-, Weiß-, Kräuter-, Früchte- und weitere Tees.',
    },
    {
      id: 'mate',
      eyebrow: '02 — Mate aus Argentinien',
      title: 'Ein Stück Argentinien in Bonn.',
      text: 'Unsere Welt beginnt beim Tee. Und manchmal führt sie bis nach Argentinien.',
    },
    {
      id: 'tableware',
      eyebrow: '03 — Geschirr',
      title: 'Für die Tea Time zu Hause.',
      text: 'Kuratiertes Geschirr, insbesondere von europäischen Herstellern aus England und Deutschland.',
    },
    {
      id: 'delicacies',
      eyebrow: '04 — Feinkost',
      title: 'Was zu gutem Tee gehört.',
      text: 'Scones mit Clotted Cream, argentinisches Gebäck, Sandwiches, Marmelade und hausgemachter Kuchen.',
    },
  ],
  salonOffer: [
    { label: 'Warmer Tee', priority: 'primary', status: 'available' },
    { label: 'Eistee', priority: 'primary', status: 'available' },
    { label: 'Alkoholfreie Tea Cocktails', priority: 'primary', status: 'available' },
    { label: 'Tea Time', priority: 'primary', status: 'available' },
    { label: 'Coffee', priority: 'secondary', status: 'available' },
    { label: 'Frühstück', priority: 'secondary', status: 'coming-soon' },
  ],
  events: [
    {
      slug: 'lupercias-teerunde',
      title: 'Lupercias Teerunde',
      category: 'Teerunde',
      date: null,
      endDate: null,
      time: null,
      description: 'Maria lädt zu einer offenen Teerunde ein – zum Kennenlernen, Austauschen und gemeinsamen Teetrinken.',
      shortDescription: 'Ein Tisch. Eine Kanne Tee. Neue Begegnungen.',
      image: null,
      price: null,
      capacity: null,
      status: 'coming-soon',
      bookingType: 'not-open',
      bookingUrl: null,
      featured: true,
      recurrence: 'Ein- bis zweimal pro Woche geplant',
    },
    {
      slug: 'tea-time-unter-frauen',
      title: 'Tea Time unter Frauen',
      category: 'Frauenrunde',
      date: null,
      endDate: null,
      time: null,
      description: 'Ein entspannter Nachmittag für Gespräche, Begegnungen und guten Tee.',
      shortDescription: 'Von einer Frau für Frauen.',
      image: null,
      price: null,
      capacity: null,
      status: 'coming-soon',
      bookingType: 'not-open',
      bookingUrl: null,
      featured: false,
      recurrence: 'Regelmäßiges Format in Vorbereitung',
    },
    {
      slug: 'tango-and-tea',
      title: 'Tango & Tea',
      category: 'Tango',
      date: '18. August',
      endDate: null,
      time: null,
      description: 'Ein besonderer Nachmittag mit Tango und gemeinsamem Tee.',
      shortDescription: 'Argentinische Kultur trifft Tea Time.',
      image: null,
      price: null,
      capacity: null,
      status: 'upcoming',
      bookingType: 'not-open',
      bookingUrl: null,
      featured: true,
      recurrence: null,
    },
    {
      slug: 'verkostungen-und-workshops',
      title: 'Verkostungen & Workshops',
      category: 'Verkostung',
      date: null,
      endDate: null,
      time: null,
      description: 'Maria führt persönlich durch ausgewählte Tees, ihre Herkunft, Zubereitung und Aromen.',
      shortDescription: 'Tee verstehen und gemeinsam probieren.',
      image: null,
      price: null,
      capacity: null,
      status: 'coming-soon',
      bookingType: 'inquiry',
      bookingUrl: null,
      featured: false,
      recurrence: null,
    },
    {
      slug: 'tea-and-books',
      title: 'Tea & Books',
      category: 'Leserunde',
      date: null,
      endDate: null,
      time: null,
      description: 'Eine Leserunde für Geschichten, Gespräche und eine gemeinsam geteilte Kanne Tee.',
      shortDescription: 'Geschichten, Gespräche und eine Kanne Tee.',
      image: null,
      price: null,
      capacity: null,
      status: 'coming-soon',
      bookingType: 'not-open',
      bookingUrl: null,
      featured: false,
      recurrence: null,
    },
    {
      slug: 'winterseminare',
      title: 'Winterseminare',
      category: 'Seminar',
      date: null,
      endDate: null,
      time: null,
      description: 'Vertiefende Seminare rund um Tee und Genuss in der kalten Jahreszeit.',
      shortDescription: 'Vertiefende Teemomente in der kalten Jahreszeit.',
      image: null,
      price: null,
      capacity: null,
      status: 'coming-soon',
      bookingType: 'not-open',
      bookingUrl: null,
      featured: false,
      recurrence: 'Im Winter geplant',
    },
  ],
  quality: {
    certifications: [],
    certificationStatus: 'not-published',
  },
  visit: {
    address: { value: 'Argelanderstraße 75, 53115 Bonn', href: 'https://www.google.com/maps/place//data=!4m2!3m1!1s0x47bee1319e495c77:0x1469500b6761ac3c', status: 'available' },
    openingHours: { value: { monday: null, tuesday: '11:00–19:00', wednesday: '11:00–19:00', thursday: '11:00–19:00', friday: '11:00–19:00', saturday: '12:00–17:00', sunday: null }, status: 'available' },
    phone: { label: '01516 7970350', href: 'tel:+4915167970350', status: 'available' },
    email: { label: 'E-Mail', href: null, status: 'not-provided' },
    reservation: { href: null, status: 'coming-soon' },
    map: { embed: null, status: 'not-configured' },
  },
  links: {
    instagram: { label: 'Instagram', href: 'https://www.instagram.com/lupercia.de/', status: 'available' },
    imprint: { label: 'Impressum', href: null, status: 'coming-soon' },
    privacy: { label: 'Datenschutz', href: null, status: 'coming-soon' },
  },
});
